// ~~~~~~~~~ EXPORT CHART CODE ~~~~~~~~~

const VIS_EXPORTS = `# Generated by AutoProfiler

import altair as alt`
const disableMaxRowsCode = 'alt.data_transformers.disable_max_rows()'

export const QUANT_CHART = (
    df_name: string,
    col_name: string,
    numbins = 8
) => {
    let col_stmt: string;
    if (col_name === "INDEX") {
        col_stmt = ".index.to_series()";
    } else {
        col_stmt = `["${col_name}"]`;
    };
    return `${VIS_EXPORTS} 
binned_series = ${df_name}${col_stmt}.value_counts(bins=${numbins}, sort=False)

chart_data_binned = pd.DataFrame({
    "leftbin": binned_series.index.left, 
    "rightbin": binned_series.index.right, 
    "count": binned_series.values
})

# move leftmost bin edge up since pandas does not put edge at the min
chart_data_binned.loc[0, "leftbin"] = ${df_name}${col_stmt}.min()

quant_chart = alt.Chart(chart_data_binned).mark_bar(color="#fca5a5").encode(
    x = alt.X("leftbin", bin="binned", title="${col_name} (binned)"),
    x2 = "rightbin",
    y = alt.Y("count")
).properties(
    width=500,
    height=200
)

quant_chart`;
}

export const CAT_CHART = (
    df_name: string,
    col_name: string,
    k = 10
) => {
    let col_stmt: string;
    if (col_name === "INDEX") {
        col_stmt = ".index.to_series()";
    } else {
        col_stmt = `["${col_name}"]`;
    };
    return `${VIS_EXPORTS}
topk_series = ${df_name}${col_stmt}.value_counts().iloc[:${k}]
topk_df = pd.DataFrame({"${col_name}":topk_series.index, 'count':topk_series.values})

cat_chart = alt.Chart(topk_df).mark_bar(color="#bae6fd").encode( 
    x = alt.X("count"),
    y = alt.Y("${col_name}", sort="-x")
).properties(
    width=500,
    height=200
)

cat_chart`;
}


export const TEMPORAL_CHART = (
    df_name: string,
    col_name: string,
    shouldDisableMaxRows = false
) => {
    let col_stmt: string;
    if (col_name == "INDEX") {
        col_stmt = ".index.to_series()";
    } else {
        col_stmt = `["${col_name}"]`;
    };
    return `${VIS_EXPORTS}
${shouldDisableMaxRows ? disableMaxRowsCode : ""}

temp_df = pd.DataFrame({"temp":${df_name}${col_stmt}})

temporal_chart = alt.Chart(temp_df).mark_line(color="#14b8a6").encode(
    x='temp:T',
    y='count()'
).properties(
    width=500,
    height=200
)

temporal_chart`;
}

// ~~~~~~~~~ EXPORT Selection CODE ~~~~~~~~~
export type CODE_EXPORT_TYPE = "min" | "25%" | "median" | "mean" | "75%" | "max";

export function exportCodeSelection(df_name: string, col_name: string, type: CODE_EXPORT_TYPE) {

    let agg_code = ""

    if (type === "min") {
        agg_code = `.min()`
    } else if (type === "25%") {
        agg_code = `.quantile(0.25)`
    } else if (type === "median") {
        agg_code = `.median()`
    } else if (type === "mean") {
        agg_code = `.mean()`
    } else if (type === "75%") {
        agg_code = `.quantile(0.75)`
    } else if (type === "max") {
        agg_code = `.max()`
    }

    if (agg_code) {
        return `${df_name}[ ${df_name}["${col_name}"] == ${df_name}["${col_name}"]${agg_code} ]`
    }

    return `${df_name}["${col_name}"]`
}
