export const QUANT_CHART = (
    df_name: string,
    col_name: string,
    maxbins = 8
) => `# Generated by AutoProfiler 
import altair as alt
quant_chart = alt.Chart(${df_name}).mark_bar(color="#fca5a5").encode(
    x = alt.X("${col_name}", bin=alt.Bin(maxbins=${maxbins})),
    y = alt.Y("count()")
).properties(
    width=500,
    height=200
)

quant_chart`;

export const CAT_CHART = (
    df_name: string,
    col_name: string,
    k = 10
) => `# Generated by AutoProfiler 
import altair as alt
topk_series = ${df_name}["${col_name}"].value_counts().iloc[:${k}]
topk_df = pd.DataFrame({"${col_name}":topk_series.index, 'count':topk_series.values})

cat_chart = alt.Chart(topk_df).mark_bar(color="#bae6fd").encode( 
    x = alt.X("count"),
    y = alt.Y("${col_name}", sort="-x")
).properties(
    width=500,
    height=200
)

cat_chart`;



// #54B5A6

export const TEMPORAL_CHART = (
    df_name: string,
    col_name: string
) => `# Generated by AutoProfiler 
import altair as alt
temporal_chart = alt.Chart(${df_name}).mark_line(color="#14b8a6").encode(
    x='${col_name}:T',
    y='count()'
).properties(
    width=500,
    height=200
)

temporal_chart`;